export enum DriverDocumentType {
  DNI_FRONT = 'DNI_FRONT',
  DNI_BACK = 'DNI_BACK',
  DRIVER_LICENSE = 'DRIVER_LICENSE',
  VEHICLE_REGISTRATION = 'VEHICLE_REGISTRATION',
  SOAT = 'SOAT',
  PROFILE_PHOTO = 'PROFILE_PHOTO',
}
