export enum DriverCancellationReason {
  PASSENGER_REQUESTED_CANCEL = 'PASSENGER_REQUESTED_CANCEL',
  CANNOT_REACH_PICKUP = 'CANNOT_REACH_PICKUP',
  VEHICLE_PROBLEM = 'VEHICLE_PROBLEM',
  SAFETY_CONCERN = 'SAFETY_CONCERN',
  PASSENGER_NOT_FOUND = 'PASSENGER_NOT_FOUND',
  EMERGENCY = 'EMERGENCY',
  OTHER = 'OTHER',
}
