export enum PassengerCancellationReason {
  CHANGED_MIND = 'CHANGED_MIND',
  DRIVER_TOO_FAR = 'DRIVER_TOO_FAR',
  DRIVER_NOT_MOVING = 'DRIVER_NOT_MOVING',
  DRIVER_REQUESTED_CANCEL = 'DRIVER_REQUESTED_CANCEL',
  WRONG_PICKUP_POINT = 'WRONG_PICKUP_POINT',
  SAFETY_CONCERN = 'SAFETY_CONCERN',
  OTHER = 'OTHER',
}
