export enum RideCancellationType {
  PASSENGER_CANCELLED = 'PASSENGER_CANCELLED',
  DRIVER_CANCELLED = 'DRIVER_CANCELLED',
  PASSENGER_NO_SHOW = 'PASSENGER_NO_SHOW',
  DRIVER_NO_SHOW_CANCELLED = 'DRIVER_NO_SHOW_CANCELLED',
}
