export enum RideLocationRejectionReason {
  STALE = 'STALE',
  FUTURE_TIMESTAMP = 'FUTURE_TIMESTAMP',
  LOW_ACCURACY = 'LOW_ACCURACY',
  OUT_OF_ORDER = 'OUT_OF_ORDER',
  TOO_FREQUENT = 'TOO_FREQUENT',
  MOVEMENT_TOO_SMALL = 'MOVEMENT_TOO_SMALL',
  IMPOSSIBLE_SPEED = 'IMPOSSIBLE_SPEED',
}
