export enum RideRatingTag {
  SAFE_DRIVING = 'SAFE_DRIVING',
  FRIENDLY = 'FRIENDLY',
  CLEAN_VEHICLE = 'CLEAN_VEHICLE',
  PUNCTUAL = 'PUNCTUAL',
  GOOD_COMMUNICATION = 'GOOD_COMMUNICATION',
  RESPECTFUL = 'RESPECTFUL',
  CLEAR_PICKUP_POINT = 'CLEAR_PICKUP_POINT',
}
